/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author LAB03M07
 */
public class jogo_GUI extends javax.swing.JFrame {

    /**
     * Creates new form jogo_GUI
     */
    public jogo_GUI() {
        initComponents();
        pedra.setVisible(false);
        tesoura.setVisible(false);
        papel.setVisible(false);
        pedra1.setVisible(false);
        tesoura1.setVisible(false);
        papel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Escolha = new javax.swing.JButton();
        pedra = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        papel = new org.edisoncor.gui.panel.PanelImage();
        tesoura = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        papel1 = new org.edisoncor.gui.panel.PanelImage();
        tesoura1 = new org.edisoncor.gui.panel.PanelImage();
        pedra1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        Escolha.setText("Escolha");
        Escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscolhaActionPerformed(evt);
            }
        });
        jPanel1.add(Escolha);
        Escolha.setBounds(410, 340, 130, 50);

        pedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pedra.png"))); // NOI18N
        pedra.setLayout(new java.awt.GridLayout());
        jPanel1.add(pedra);
        pedra.setBounds(810, 160, 120, 100);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Jokenpo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(430, 10, 70, 30);

        papel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/papel.png"))); // NOI18N

        javax.swing.GroupLayout papelLayout = new javax.swing.GroupLayout(papel);
        papel.setLayout(papelLayout);
        papelLayout.setHorizontalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        papelLayout.setVerticalGroup(
            papelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papel);
        papel.setBounds(550, 160, 120, 100);

        tesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesouraLayout = new javax.swing.GroupLayout(tesoura);
        tesoura.setLayout(tesouraLayout);
        tesouraLayout.setHorizontalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesouraLayout.setVerticalGroup(
            tesouraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesoura);
        tesoura.setBounds(690, 160, 100, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jogador");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 80, 90, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Computador");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(720, 90, 90, 14);
        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, -30, 100, 100);

        papel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/papel.png"))); // NOI18N

        javax.swing.GroupLayout papel1Layout = new javax.swing.GroupLayout(papel1);
        papel1.setLayout(papel1Layout);
        papel1Layout.setHorizontalGroup(
            papel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        papel1Layout.setVerticalGroup(
            papel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(papel1);
        papel1.setBounds(170, 160, 120, 100);

        tesoura1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tesoura.png"))); // NOI18N

        javax.swing.GroupLayout tesoura1Layout = new javax.swing.GroupLayout(tesoura1);
        tesoura1.setLayout(tesoura1Layout);
        tesoura1Layout.setHorizontalGroup(
            tesoura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        tesoura1Layout.setVerticalGroup(
            tesoura1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(tesoura1);
        tesoura1.setBounds(310, 160, 100, 100);

        pedra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pedra.png"))); // NOI18N

        javax.swing.GroupLayout pedra1Layout = new javax.swing.GroupLayout(pedra1);
        pedra1.setLayout(pedra1Layout);
        pedra1Layout.setHorizontalGroup(
            pedra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        pedra1Layout.setVerticalGroup(
            pedra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(pedra1);
        pedra1.setBounds(20, 160, 120, 100);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setText("X");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(470, 170, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(931, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscolhaActionPerformed
        int jogador = 0;  
        String x =  JOptionPane.showInputDialog(null,"Escolha sua jogada\n 0-pedra\n1-tesoura\n2-papel");
        jogador = Integer.parseInt(x); 
        if(jogador == 0){
            pedra1.setVisible(true);
            papel1.setVisible(false);
            tesoura1.setVisible(false);
        }else if(jogador == 1){
            tesoura1.setVisible(true);
            pedra1.setVisible(false);
            papel1.setVisible(false);
        }else{
            papel1.setVisible(true);
             tesoura1.setVisible(false);
            pedra1.setVisible(false);
        }
           Random gerador = new Random();
        int pc = gerador.nextInt(3);
        if(pc == 0){
            pedra.setVisible(true);
            papel.setVisible(false);
            tesoura.setVisible(false);
        }else if(pc == 1){
            tesoura.setVisible(true);
            papel.setVisible(false);
            pedra.setVisible(false);
            
        }else{
            papel.setVisible(true);
            pedra.setVisible(false);
            tesoura.setVisible(false);
        }  
            
        
    }//GEN-LAST:event_EscolhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jogo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jogo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jogo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jogo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jogo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Escolha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.edisoncor.gui.panel.PanelImage papel;
    private org.edisoncor.gui.panel.PanelImage papel1;
    private org.edisoncor.gui.panel.PanelImage pedra;
    private org.edisoncor.gui.panel.PanelImage pedra1;
    private org.edisoncor.gui.panel.PanelImage tesoura;
    private org.edisoncor.gui.panel.PanelImage tesoura1;
    // End of variables declaration//GEN-END:variables
}
